package org.openshift.quickstarts.decisionserver.hellorules

query "get greeting"()
    greeting : Greeting()
end

rule "greet master"
    when
        person : Person( name == "rettori")
    then
        String salutation = "Hello " + person.getName() + "! you really rock!";
        insert(new Greeting(salutation));
end
rule "greet strangers"
    when
        person : Person( name != "rettori")
    then
        String salutation = "Come on man, get out of my way " + person.getName();
        insert(new Greeting(salutation));
end
